[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"

[build]
rustflags = ["-C", "force-frame-pointers"]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]

[alias]
br = "build --release"
ff = "run --release"
