[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip esp32c6"
rustflags = [
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
